@baseUrl = http://localhost:3000
@admin_token = {{admin_token}}
@user_id = {{user_id}}

# Admin 取得全部使用者限制紀錄
GET {{baseUrl}}/restrict-user
Authorization: Bearer {{admin_token}}

###
# Admin 取得特定使用者限制紀錄
GET {{baseUrl}}/restrict-user/{{user_id}}
Authorization: Bearer {{admin_token}}
