@baseUrl = http://localhost:3000
@admin_token = {{admin_token}}
@user_id = {{user_id}}

# Admin 建立使用者限制紀錄
POST {{baseUrl}}/restrict-user
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "userID": "{{user_id}}",
  "originalState": 0,
  "latestState": 1
}
