#  /**
#    * API 功能：
#    * GET url/subscriptions                         => 取得所有訂閱關係
#    * GET url/subscriptions/user/:userID            => 取得某 User 的所有訂閱
#    * GET url/subscriptions/merchant/:merchantID    => 取得某 Merchant 的所有訂閱者
#    * GET url/subscriptions/:userID/:merchantID     => 取得特定訂閱關係
#    */

# ----------
# 請先在 member 建立 user 和 merchant，並取得他們的 ID
# 執行 POST.http 建立訂閱後，再來測試這些 GET API
# ----------

@user1_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZjhjODcxMS04MGI1LTQ0OTUtOGU1ZS03NzU0YzAxOTgwYjUiLCJhY2NvdW50IjoidXNlci10ZXN0LTEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2MzgxOTIwOSwiZXhwIjoxNzYzOTA1NjA5fQ._RTbrhb4j3EBrqwIu-oZ9bPKNimdcPuWJGqIOYx0A0M
@user2_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWQ3MWEzYy00NmJkLTRkMzQtYjZkNy1mZWY2YWY5NmM3YzciLCJhY2NvdW50IjoidXNlci10ZXN0LTIiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2MzgxOTIyNSwiZXhwIjoxNzYzOTA1NjI1fQ.7sD_J0pXOzEuxUm9z5sdbygl2QU-whKOAlWLWBZfdOs
@user1_id = 9f8c8711-80b5-4495-8e5e-7754c01980b5
@user2_id = 61d71a3c-46bd-4d34-b6d7-fef6af96c7c7
@merchant1_id = 2037df73-aa38-4426-abba-9bf578e6fe44
@merchant2_id = 81afb742-89e2-43d2-8bb2-f88c2bba4a94
@user1_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MGI2ZmJmYS1mOGU0LTRkNjEtODBlZS00MjEyZjljYzZmMzkiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2NTk0MDA3OCwiZXhwIjoxNzY2MDI2NDc4fQ.wxDSRsK11PUZ50pr6K3eGyPKEwbVdPjEwuDIPZtzWE0
@merchant1_token = dafsefsfdf



### 取得某 User 的所有訂閱
GET http://localhost:3000/subscriptions/user
Authorization: Bearer {{user1_token}}

### 取得某 Merchant 的所有訂閱者
# GET http://localhost:3000/subscriptions/merchant/
# Authorization: Bearer {{merchant1_token}}

### 取得特定訂閱關係
GET http://localhost:3000/subscriptions/isUserSubscribedToMerchant/{{merchant1_id}}
Authorization: Bearer {{user1_token}}
