#  /**
#    * API 功能：
#    * PATCH url/subscriptions/:userID/:merchantID + body => 更新通知設定 (需要 JWT 認證)
#    *   - body: { notificationEnabled }
#    *   - notificationEnabled: true 或 false
#    *
#    * 權限說明：
#    *   - User: 只能更新自己的訂閱
#    *   - Admin: 可以更新任何人的訂閱
#    */

# ----------
# 請先執行 POST.http 建立訂閱
# 並確保 token 是有效的
# ----------

@user1_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MGI2ZmJmYS1mOGU0LTRkNjEtODBlZS00MjEyZjljYzZmMzkiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2NTk0MDA3OCwiZXhwIjoxNzY2MDI2NDc4fQ.wxDSRsK11PUZ50pr6K3eGyPKEwbVdPjEwuDIPZtzWE0
@merchant1_id = 2037df73-aa38-4426-abba-9bf578e6fe44


### User 關閉通知 => 成功
PATCH http://localhost:3000/subscriptions/{{merchant1_id}}
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "notificationEnabled": false
}

### User 開啟通知 => 成功
PATCH http://localhost:3000/subscriptions/{{merchant1_id}}
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "notificationEnabled": true
}

# ### Admin 更新任何人的訂閱 => 成功
# PATCH http://localhost:3000/subscriptions/{{user2_id}}/{{merchant1_id}}
# Content-Type: application/json
# Authorization: Bearer {{admin_token}}

# {
#   "notificationEnabled": true
# }

### 未帶 token 更新訂閱 => 失敗 401 Unauthorized
# PATCH http://localhost:3000/subscriptions/{{user1_id}}/{{merchant1_id}}
# Content-Type: application/json

# {
#   "notificationEnabled": false
# }

