#  /**
#    * API 功能：
#    * POST url/subscriptions + body => 建立訂閱 (需要 JWT 認證)
#    *   - body: { userID, merchantID, notificationEnabled? }
#    *   - notificationEnabled: true 或 false (預設 false，是否開啟通知)
#    *
#    * 權限說明：
#    *   - User: 只能為自己訂閱
#    *   - Admin: 可以為任何人訂閱
#    */

# ----------
# 請先在 member 建立 user 和 merchant
# 並執行 member/test-api/POST.http 中的登入 API 取得 token
# ----------

# 先登入取得 token (請先執行 member/test-api/POST.http 中的登入 API)
@user1_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MGI2ZmJmYS1mOGU0LTRkNjEtODBlZS00MjEyZjljYzZmMzkiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2NTk0MDA3OCwiZXhwIjoxNzY2MDI2NDc4fQ.wxDSRsK11PUZ50pr6K3eGyPKEwbVdPjEwuDIPZtzWE0
@user2_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWQ3MWEzYy00NmJkLTRkMzQtYjZkNy1mZWY2YWY5NmM3YzciLCJhY2NvdW50IjoidXNlci10ZXN0LTIiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2MzgxOTIyNSwiZXhwIjoxNzYzOTA1NjI1fQ.7sD_J0pXOzEuxUm9z5sdbygl2QU-whKOAlWLWBZfdOs
@user1_id = 9f8c8711-80b5-4495-8e5e-7754c01980b5
@user2_id = 61d71a3c-46bd-4d34-b6d7-fef6af96c7c7
@merchant1_id = 2037df73-aa38-4426-abba-9bf578e6fe44
@merchant2_id = 2037df73-aa38-4426-abba-9bf578e6fe44


### User1 為自己建立訂閱 => 成功
POST http://localhost:3000/subscriptions
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "merchantID": "{{merchant1_id}}",
  "notificationEnabled": false
}

### User2 為自己建立訂閱 => 成功
POST http://localhost:3000/subscriptions
Content-Type: application/json
Authorization: Bearer {{user2_token}}

{
  "merchantID": "{{merchant1_id}}",
  "notificationEnabled": false
}

### User1 為自己建立訂閱（開啟通知）=> 成功
POST http://localhost:3000/subscriptions
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "merchantID": "{{merchant2_id}}",
  "notificationEnabled": true
}

### 重複訂閱 => 失敗 409 Conflict "Subscription already exists"
POST http://localhost:3000/subscriptions
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "merchantID": "{{merchant1_id}}",
  "notificationEnabled": true
}

