#  /**
#    * API 功能：
#    * GET url/members/me         => 取得自己的資料 (需帶 Access Token)
#    * GET url/members/me/level   => 取得並更新會員等級 (需帶 User 的 Access Token)
#    * GET url/members            => 所有member
#    * GET url/members/:id        => 用id找member
#    * GET url/members/:id/type   => 用id找member的type
#    */

@admin_id = 81dc3b42-d706-4b88-8e79-4f1ed93b56e6
@user_id = 31fde60e-6b3a-4910-ae22-a484e27764aa
@merchant_id = 0281a18a-b682-40ae-bff3-bddaf041fa57
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMzE3NzI3NS1mMjIxLTRlZjItOGQzYi04NTUyOGMxOTMwZTIiLCJhY2NvdW50IjoibWVyY2hhbnQxIiwidHlwZSI6Im1lcmNoYW50IiwiaWF0IjoxNzY3MTAxMzIxLCJleHAiOjE3NjcxODc3MjF9.1fOIjwpoNTPfruELbqAjzQG1kGwaupN26kZXxBhH4XM

@user_access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmJhYjdmYy05NGEyLTRhNjAtYTk0Yy0wYzFiMmFkMjk0NTYiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2NzEwMDkzNSwiZXhwIjoxNzY3MTg3MzM1fQ.ra7wiivIozAGiyeUsFtgnijcSudxFNhXQ9HvcS1lono



### 拿回所有members的資料
GET http://localhost:3000/members


### 拿回自己的資料
GET http://localhost:3000/members/me
Authorization: Bearer {{access_token}}


### 查詢會員等級並更新 (User only)
# 回傳格式: { level: number, totalSpent: number }
# Level 規則:
#   Level 1: 總消費 < 5000
#   Level 2: 總消費 >= 5000
#   Level 3: 總消費 >= 10000
#   Level 4: 總消費 >= 15000
GET http://localhost:3000/members/me/level
Authorization: Bearer {{user_access_token}}


### 拿回某成員的資料
GET http://localhost:3000/members/81dc3b42-d706-4b88-8e79-4f1ed93b56e6
###
GET http://localhost:3000/members/c51e392e-e109-4789-a2ca-ebb8cd29c56a
###
GET http://localhost:3000/members/0281a18a-b682-40ae-bff3-bddaf041fa57

### 拿回某成員的type
GET http://localhost:3000/members/81dc3b42-d706-4b88-8e79-4f1ed93b56e6/type
###
GET http://localhost:3000/members/31fde60e-6b3a-4910-ae22-a484e27764aa/type
###
GET http://localhost:3000/members/0281a18a-b682-40ae-bff3-bddaf041fa57/type

### Merchant 拿回自己的詳細資料以及自己的商品
GET http://localhost:3000/members/merchantWithBooks
Authorization: Bearer {{access_token}}

### User 想瀏覽該商家賣什麼
GET http://localhost:3000/members/MerchantInfoWithBook/ef450ad3-3d09-4f78-bcbe-70cfe880d224


### Merchant 拿回自己的詳細資料以及自己的商品
GET http://localhost:3000/members/merchantWithBooks
Authorization: Bearer {{access_token}}

### Merchant 拿回自己的 canAcceptOrder
GET http://localhost:3000/members/canAcceptOrder
Authorization: Bearer {{access_token}}

### User 拿回自己的 canCreateReview
GET http://localhost:3000/members/canCreateReview
Authorization: Bearer {{user_access_token}}

### User 拿回自己的 canCreateOrder
GET http://localhost:3000/members/canCreateOrder
Authorization: Bearer {{user_access_token}}