#   @url = http://localhost:3000
#   /**
#    * API 功能：
#    * GET url/members            => 所有member
#    * GET url/members/:id        => 用id找member
#    * GET url/members/:id/type   => 用id找member的type
#    * POST url/member + body     => 新增member資料，並回傳member
#    *   - email account password phoneNumber type              => member皆有，type = "admin" or "user" or "merchant" 
#    *   - username level userState                             => type = "user" 會有的
#    *   - merchantsName merchantsState address subscriberCount => type = "merchant" 會有的
#    */
@baseUrl = http://localhost:3000

### 測試建立新admin
POST http://localhost:3000/members
Content-Type: application/json

{
  "email": "test-admin@example.com",
  "account": "admin-test-1",
  "password": "0000",
  "phone": "0912345678",
  "type": "admin"
}


### 測試建立新user
POST http://localhost:3000/members
Content-Type: application/json

{
  "email": "test-user@example.com",
  "account": "user-test-1",
  "password": "0000",
  "phone": "0911222333",
  "type": "user",
  "username": "User1"
}

### 測試建立新merchant
POST http://localhost:3000/members
Content-Type: application/json

{
  "email": "test-merchant@example.com",
  "account": "merchant-test-1",
  "password": "0000",
  "phone": "0911222333",
  "type": "merchant",
  "merchantsName": "Merchant1",
  "address": "New TaipeiCity"
}