#  /**
#    * API 功能：
#    *
#    * POST url/members + body     => 新增member資料，並回傳member
#    *   - email account password phoneNumber type              => member皆有，type = "admin" or "user" or "merchant"
#    *   - username level                                       => type = "user" 會有的
#    *   - merchantsName address => type = "merchant" 會有的    => type = "merchant" 會有的
#    * 
#    * POST url/members/login + body   => 登入member，回傳JWT access token和會員資料
#    *   - body :
#    *   - account password
#    */

# ----------
#  若某資料重複會回覆 "xxx already Exist."
#  xxx => Email、Account、Phone number、Merchant name
# ----------
@baseUrl = http://localhost:3000

### 測試建立新admin
POST http://localhost:3000/members
Content-Type: application/json

{
  "email": "test-admin@example.com",
  "account": "admin-test-1",
  "password": "0000",
  "phoneNumber": "0912345678",
  "type": "admin"
}


### 測試建立新user
POST http://localhost:3000/members
Content-Type: application/json

{
  "email": "test-user@example.com",
  "account": "user-test-1",
  "password": "0000",
  "phoneNumber": "0911222333",
  "type": "user",
  "username": "User1"
}

### 測試建立新merchant
POST http://localhost:3000/members
Content-Type: application/json

{
  "email": "test-merchant@example.com",
  "account": "merchant-test-1",
  "password": "0000",
  "phoneNumber": "0944555666",
  "type": "merchant",
  "merchantsName": "Merchant1",
  "address": "New TaipeiCity"
}


### User 登入 API 測試
POST http://localhost:3000/members/login
Content-Type: application/json

{
  "account": "user-test-1",
  "password": "0000"
}
### Admin 登入 API 測試

POST http://localhost:3000/members/login
Content-Type: application/json

{
  "account": "admin-test-1",
  "password": "0000"
}

### 登入失敗測試 - 錯誤密碼
POST http://localhost:3000/members/login
Content-Type: application/json

{
  "account": "user-test-1",
  "password": "1111"
}

### 登入失敗測試 - 不存在的帳號
POST http://localhost:3000/members/login
Content-Type: application/json

{
  "account": "nonexistuser",
  "password": "0000"
}
