@baseUrl = http://localhost:3000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiODMzMzA5Ny0zNmI0LTQ0OWMtOTY4Ni00ZmFmOWViNDU4ZDUiLCJhY2NvdW50IjoidXNlcjIiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2Njk4Mzc4NSwiZXhwIjoxNzY3MDcwMTg1fQ.AhH2IQoRdrwvrrVoQUGoAn0YU03tVJO4eo6k_nb6F7c
@admin_token = {{admin_token}}     // 管理員 access token
@claim_id = 9ec436c6-695d-4592-98c1-5b42e6bf2e58

# 管理員或本人刪除領券紀錄
DELETE {{baseUrl}}/claims/{{claim_id}}
Authorization: Bearer {{access_token}}
