@baseUrl = http://localhost:3000
@access_token =
@admin_token =
@claim_id = {{claim_id}}

# 刪除自己的領券紀錄
DELETE {{baseUrl}}/claims/{{claim_id}}
Authorization: Bearer {{access_token}}

###
# Admin 刪除任意領券紀錄
DELETE {{baseUrl}}/claims/{{claim_id}}
Authorization: Bearer {{admin_token}}
