@baseUrl = http://localhost:3000
@access_token =
@admin_token =
@claim_id = {{claim_id}}

# 取得自己領到的優惠券
GET {{baseUrl}}/claims/mine
Authorization: Bearer {{access_token}}

###
# Admin 取得全部領券資料
GET {{baseUrl}}/claims
Authorization: Bearer {{admin_token}}

###
# 依 ClaimID 取得單一領券（Admin 可看全部，User 只能看自己）
GET {{baseUrl}}/claims/{{claim_id}}
Authorization: Bearer {{access_token}}
