@baseUrl = http://localhost:3000
@access_token =
@admin_token =
@coupon_id = {{coupon_id}}
@user_id = {{user_id}}

# 更新自己的領券剩餘數量（Admin 或持有者）
PATCH {{baseUrl}}/claims/{{coupon_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "remaining": 3
}

###
# Admin 更新指定使用者的領券
PATCH {{baseUrl}}/claims/{{coupon_id}}?userID={{user_id}}
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "remaining": 5
}
