@baseUrl = http://localhost:3000
@access_token = {{user_access_token}}       // 使用者 token 範例

# 使用者兌換優惠碼領取優惠券
POST {{baseUrl}}/claims
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "redemptionCode": "REDEMPTION_CODE_SAMPLE"
}
