@baseUrl = http://localhost:3000
@access_token = {{access_token}}
@admin_token = {{admin_token}}
@coupon_id = {{coupon_id}}

# 刪除優惠券（Admin 或擁有者）
DELETE {{baseUrl}}/coupons/{{coupon_id}}
Authorization: Bearer {{access_token}}
