@baseUrl = http://localhost:3000
@admin_token = {{admin_token}}         // 管理員 access token 範例
@merchant_token = {{merchant_token}}   // 商家 access token 範例
@coupon_id = {{coupon_id}}

# 商家或管理員刪除自己的優惠券
DELETE {{baseUrl}}/coupons/{{coupon_id}}
Authorization: Bearer {{merchant_token}}
