@baseUrl = http://localhost:3000
@access_token = {{access_token}}       // 商家/使用者 token 範例
@admin_token = {{admin_token}}         // 管理員 token 範例
@coupon_id = {{coupon_id}}

# 取得自己擁有的優惠券（需 token）
GET {{baseUrl}}/coupons/mine
Authorization: Bearer {{access_token}}

###
# Admin 取得全部優惠券
GET {{baseUrl}}/coupons
Authorization: Bearer {{admin_token}}

###
# 依 ID 取得單一優惠券（Admin 可看全部，User/Merchant 只能看自己）
GET {{baseUrl}}/coupons/{{coupon_id}}
Authorization: Bearer {{access_token}}
