@baseUrl = http://localhost:3000
@admin_token = {{admin_token}}         // 管理員 access token 範例
@merchant_token = {{merchant_token}}   // 商家 access token 範例
@admin_id = {{admin_id}}
@merchant_id = {{merchant_id}}

# Admin 建立全商城優惠券（只能給自己）
POST {{baseUrl}}/coupons
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "quantity": 100,
  "validDate": "2025-12-31T00:00:00Z",
  "discount": 0.9,
  "description": "年末特價",
  "redemptionCode": "PLATFORM-NEWYEAR-90",
  "discountType": 0,
  "memberID": "{{admin_id}}"
}

###
# 商家建立自家優惠券（只能給自己）
POST {{baseUrl}}/coupons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NWI5ZTcwNy01MDA3LTQ2ODMtYTI1NC1jYzE1ZThjMjBlODUiLCJhY2NvdW50IjoibWVyY2hhbnQxIiwidHlwZSI6Im1lcmNoYW50IiwiaWF0IjoxNzY2OTgzODY5LCJleHAiOjE3NjcwNzAyNjl9.4Z-5WgJKBigzF3K0kzVlRvdbiGfRQ5F_KLlY5Tkkdm0

{
  "quantity": 50,
  "discount": 0.8,
  "description": "新客八折券",
  "redemptionCode": "SHOP-WELCOME-80",
  "discountType": 1,
  "memberID": "55b9e707-5007-4683-a254-cc15e8c20e85"
}
