@baseUrl = http://localhost:3000
@access_token = {{access_token}}   // 使用者 access token
@book_id = {{book_id}}

# 刪除自己的評論
DELETE {{baseUrl}}/reviews/{{book_id}}
Authorization: Bearer {{access_token}}
