@baseUrl = http://localhost:3000
@access_token = {{access_token}}   // 使用者 access token
@book_id = {{book_id}}

# 新增評論
POST {{baseUrl}}/reviews
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "bookID": "{{book_id}}",
  "date": "2025-12-27",
  "stars": 5,
  "description": "很棒的書！"
}
