@baseUrl = http://localhost:3000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMzFlYTg3Ny0xY2U3LTRmZWItOGY2MS1mN2M3MThmNzY5MTAiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2Njk4NDk0MywiZXhwIjoxNzY3MDcxMzQzfQ.4DUa1qwtc3N__dxs07S7FkZyucGY96bU5j8rICZnYck

@book_id = 71bd79be-c3f2-4372-aa57-1fb7916f6bd4

# 取消收藏
DELETE {{baseUrl}}/favorites/{{book_id}}
Authorization: Bearer {{access_token}}
