@baseUrl = http://localhost:3000
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTJlNmQ5My02NDdmLTRiY2YtYTY5ZC01MjRlODU5YmFjMGIiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2NzA3NDA3MywiZXhwIjoxNzY3MTYwNDczfQ.b0f0VeTjFC82BDy9Wed0AfgHB82LDFwUAW0fbNELff0
@merchantId = 739e504f-e07d-4af1-84f3-33c11e97868e
@couponId = 950ce1cd-0b60-4ac7-9069-f09ab41e440c

### 結帳（從購物車、指定商家，支援優惠券）
POST {{baseUrl}}/orders/checkout
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "shippingAddress": "台北市信義區仁愛路100號",
  "paymentMethod": 1,
  "merchantId": "{{merchantId}}",
  "couponId": "{{couponId}}"
}

### 結帳（無優惠券）
POST {{baseUrl}}/orders/checkout
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "shippingAddress": "台北市信義區仁愛路100號",
  "paymentMethod": 1,
  "merchantId": "{{merchantId}}"
}
