@baseUrl = http://localhost:3000
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTJlNmQ5My02NDdmLTRiY2YtYTY5ZC01MjRlODU5YmFjMGIiLCJhY2NvdW50IjoidXNlcjEiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc2NzA3MTgyMywiZXhwIjoxNzY3MTU4MjIzfQ.Vmme-0jKzARhAmDiXngwTtCXM0B8FhW8znzPXb_NZw4
@merchantId = f43bc9d6-039f-4770-89c8-4d932c4cab77
@claimId = 378c9184-a60b-4e00-866f-a6d3791f9416

### 結帳（從購物車、指定商家，支援優惠券）
POST {{baseUrl}}/orders/checkout
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "shippingAddress": "台北市信義區仁愛路100號",
  "paymentMethod": 1,
  "merchantId": "{{merchantId}}",
  "claimId": "{{claimId}}"
}

### 結帳（無優惠券）
POST {{baseUrl}}/orders/checkout
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "shippingAddress": "台北市信義區仁愛路100號",
  "paymentMethod": 1,
  "merchantId": "{{merchantId}}"
}
